<a href="https://colab.research.google.com/github/eshita-3104/DSDBAL/blob/main/pract1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd
import numpy as np

In [78]:
df = pd.read_csv("/content/sample_data/Placement.csv")
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,NaN,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          213 non-null    object
 2   ssc_p           213 non-null    float64
 3   ssc_b           214 non-null    object
 4   hsc_p           214 non-null    float64
 5   hsc_b           213 non-null    object
 6   hsc_s           213 non-null    object
 7   degree_p        213 non-null    float64
 8   degree_t        214 non-null    object
 9   workex          213 non-null    object
 10  etest_p         213 non-null    float64
 11  specialisation  213 non-null    object
 12  mba_p           213 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [80]:
df.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [81]:
df.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [82]:
df.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,213.000000,214.000000,213.000000,213.000000,213.000000,148.000000
mean,108.000000,67.372911,66.344065,66.388404,72.219390,62.266103,288655.405405
std,62.209324,10.811464,10.921885,7.256840,13.255118,5.837303,93457.452420
min,1.000000,40.890000,37.000000,50.200000,50.000000,51.210000,200000.000000
25%,54.500000,60.800000,60.850000,61.000000,60.000000,57.900000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,76.000000,73.000000,72.000000,84.000000,66.230000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [83]:
df.isna().sum()

sl_no              0
gender             2
ssc_p              2
ssc_b              1
hsc_p              1
hsc_b              2
hsc_s              2
degree_p           2
degree_t           1
workex             2
etest_p            2
specialisation     2
mba_p              2
status             0
salary            67
dtype: int64

In [84]:
df['gender'].fillna(df['gender'].mode()[0], inplace=True)
df['ssc_p'].fillna(df['ssc_p'].mean(), inplace=True)
df['ssc_b'].fillna(df['ssc_b'].mode()[0], inplace=True)
df['hsc_p'].fillna(df['hsc_p'].mean(), inplace=True)
df['hsc_b'].fillna(df['hsc_b'].mode()[0], inplace=True)
df['hsc_s']=df['hsc_s'].replace(to_replace= np.nan, value="unknown")
df['degree_p'].fillna(df['degree_p'].mean(), inplace=True)
df['degree_t'].fillna(df['degree_t'].mode()[0], inplace=True)
df['workex']= df['workex'].replace(to_replace = np.nan, value="unknown")

In [85]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [86]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [87]:
df.isna().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            2
specialisation     2
mba_p              2
status             0
salary            67
dtype: int64

In [88]:
df.drop(['mba_p','specialisation'],axis=1,inplace=True)

In [89]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Not Placed,NaN

In [90]:
df['salary'].fillna(df['salary'].mean(), inplace=True)
df['etest_p'].fillna(df['etest_p'].mean(), inplace=True)

In [91]:
df.isna().sum()

sl_no       0
gender      0
ssc_p       0
ssc_b       0
hsc_p       0
hsc_b       0
hsc_s       0
degree_p    0
degree_t    0
workex      0
etest_p     0
status      0
salary      0
dtype: int64

In [92]:
df.dtypes

sl_no         int64
gender       object
ssc_p       float64
ssc_b        object
hsc_p       float64
hsc_b        object
hsc_s        object
degree_p    float64
degree_t     object
workex       object
etest_p     float64
status       object
salary      float64
dtype: object

In [93]:
df['sl_no']=df['sl_no'].astype('int8')
print('Change in datatype: ', df['sl_no'].dtypes)

Change in datatype:  int8

In [94]:
df['gender'].replace(['M','F'],[0,1],inplace=True)
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,status,salary
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Placed,270000.000000
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Placed,200000.000000
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Placed,250000.000000
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Not Placed,288655.405405
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,-45,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Placed,400000.000000
211,-44,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Placed,275000.000000
212,-43,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Placed,295000.000000
213,-42,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Placed,204000.000000
214,-41,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Not Placed,288655.405405

In [95]:
df['ssc_b']=df['ssc_b'].astype('category')
df['ssc_b']=df['ssc_b'].cat.codes

In [96]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,status,salary
0,1,0,67.00,1,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Placed,270000.000000
1,2,0,79.33,0,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Placed,200000.000000
2,3,0,65.00,0,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Placed,250000.000000
3,4,0,56.00,0,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Not Placed,288655.405405
4,5,0,85.80,0,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,-45,0,80.60,1,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Placed,400000.000000
211,-44,0,58.00,1,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Placed,275000.000000
212,-43,0,67.00,1,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Placed,295000.000000
213,-42,1,74.00,1,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Placed,204000.000000
214,-41,0,62.00,0,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Not Placed,288655.405405

In [97]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
df[['hsc_b']]=enc.fit_transform(df[['hsc_b']])

In [98]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,status,salary
0,1,0,67.00,1,91.00,1.0,Commerce,58.00,Sci&Tech,No,55.0,Placed,270000.000000
1,2,0,79.33,0,78.33,1.0,Science,77.48,Sci&Tech,Yes,86.5,Placed,200000.000000
2,3,0,65.00,0,68.00,0.0,Arts,64.00,Comm&Mgmt,No,75.0,Placed,250000.000000
3,4,0,56.00,0,52.00,0.0,Science,52.00,Sci&Tech,No,66.0,Not Placed,288655.405405
4,5,0,85.80,0,73.60,0.0,Commerce,73.30,Comm&Mgmt,No,96.8,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,-45,0,80.60,1,82.00,1.0,Commerce,77.60,Comm&Mgmt,No,91.0,Placed,400000.000000
211,-44,0,58.00,1,60.00,1.0,Science,72.00,Sci&Tech,No,74.0,Placed,275000.000000
212,-43,0,67.00,1,67.00,1.0,Commerce,73.00,Comm&Mgmt,Yes,59.0,Placed,295000.000000
213,-42,1,74.00,1,66.00,1.0,Commerce,58.00,Comm&Mgmt,No,70.0,Placed,204000.000000
214,-41,0,62.00,0,58.00,1.0,Science,53.00,Comm&Mgmt,No,89.0,Not Placed,288655.405405

In [99]:
from sklearn.preprocessing import OrdinalEncoder
enc1 = OrdinalEncoder()
df[['hsc_s']]=enc1.fit_transform(df[['hsc_s']])

In [100]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,status,salary
0,1,0,67.00,1,91.00,1.0,1.0,58.00,Sci&Tech,No,55.0,Placed,270000.000000
1,2,0,79.33,0,78.33,1.0,2.0,77.48,Sci&Tech,Yes,86.5,Placed,200000.000000
2,3,0,65.00,0,68.00,0.0,0.0,64.00,Comm&Mgmt,No,75.0,Placed,250000.000000
3,4,0,56.00,0,52.00,0.0,2.0,52.00,Sci&Tech,No,66.0,Not Placed,288655.405405
4,5,0,85.80,0,73.60,0.0,1.0,73.30,Comm&Mgmt,No,96.8,Placed,425000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,-45,0,80.60,1,82.00,1.0,1.0,77.60,Comm&Mgmt,No,91.0,Placed,400000.000000
211,-44,0,58.00,1,60.00,1.0,2.0,72.00,Sci&Tech,No,74.0,Placed,275000.000000
212,-43,0,67.00,1,67.00,1.0,1.0,73.00,Comm&Mgmt,Yes,59.0,Placed,295000.000000
213,-42,1,74.00,1,66.00,1.0,1.0,58.00,Comm&Mgmt,No,70.0,Placed,204000.000000
214,-41,0,62.00,0,58.00,1.0,2.0,53.00,Comm&Mgmt,No,89.0,Not Placed,288655.405405

In [101]:
#normalization
df['salary'] = (df['salary']-df['salary'].min())/(df['salary'].max()-df['salary'].min())

In [102]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,status,salary
0,1,0,67.00,1,91.00,1.0,1.0,58.00,Sci&Tech,No,55.0,Placed,0.094595
1,2,0,79.33,0,78.33,1.0,2.0,77.48,Sci&Tech,Yes,86.5,Placed,0.000000
2,3,0,65.00,0,68.00,0.0,0.0,64.00,Comm&Mgmt,No,75.0,Placed,0.067568
3,4,0,56.00,0,52.00,0.0,2.0,52.00,Sci&Tech,No,66.0,Not Placed,0.119805
4,5,0,85.80,0,73.60,0.0,1.0,73.30,Comm&Mgmt,No,96.8,Placed,0.304054
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,-45,0,80.60,1,82.00,1.0,1.0,77.60,Comm&Mgmt,No,91.0,Placed,0.270270
211,-44,0,58.00,1,60.00,1.0,2.0,72.00,Sci&Tech,No,74.0,Placed,0.101351
212,-43,0,67.00,1,67.00,1.0,1.0,73.00,Comm&Mgmt,Yes,59.0,Placed,0.128378
213,-42,1,74.00,1,66.00,1.0,1.0,58.00,Comm&Mgmt,No,70.0,Placed,0.005405
214,-41,0,62.00,0,58.00,1.0,2.0,53.00,Comm&Mgmt,No,89.0,Not Placed,0.119805